// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzpsigetmhyvfvdxcdvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cHNpZ2V0bWh5dmZ2ZHhjZHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDA0NDIsImV4cCI6MjA3MjU3NjQ0Mn0.jChhhoJEuhUTh3DGLTPWx6FseAjbYNAUO9vzTtjjt8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});